# Generated by Django 3.1.2 on 2022-02-26 13:35

import ahang.validators
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ahang_esm', models.CharField(default=None, max_length=500)),
                ('ahang_file', models.FileField(upload_to='Musics/', validators=[ahang.validators.validate_file])),
                ('publishDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('isAgreed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': "Music's",
            },
        ),
        migrations.CreateModel(
            name='CommentDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('ahang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ahang.ahang')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
